### ISSUE TITLE
Mention that `links` is mandatory (unlike to docker compose)

### ISSUE THREAD

**Issue by adius** [hyperhq/docs.hyper.sh#109]
From https://docs.docker.com/compose/compose-file/compose-versioning:

> By default, every container joins an application-wide default network, and is discoverable at a hostname that’s the same as the service name. This means links are largely unnecessary.

In hyper however it only seems to work if the link is explicitly specified.

For example in following compose file the links should not be necessary:

```yaml
version: '2'
services:
  mongo:
    image: mongo
    expose:
      - 27017
  app:
    image: some-nodejs-app
    fip: 185.232.231.123
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3000:3000
```
